parameters:
    phy_cache.client.class: PHY\CacheBundle\Cache\Memcache
    phy_cache.client.settings:
      server: [ '127.0.0.1:11211' ]
    phy_cache.prefix: 'phy_'
    phy_cache.class: PHY\CacheBundle\Cache
    phy_cache.expiration: 300
    phy_cache.compress: 0